### ISSUE TITLE
Build failure on future branch

### ISSUE THREAD

**Issue by catbusstop** [justinmeza/lci#32]
I can build the main branch fine, but the lci-future branch fails to build for me. The output of make.out is as follows:

Scanning dependencies of target lci
[ 10%] Building C object CMakeFiles/lci.dir/interpreter.c.obj
[ 20%] Building C object CMakeFiles/lci.dir/lexer.c.obj
[ 30%] Building C object CMakeFiles/lci.dir/main.c.obj
C:\temp\lci-future\main.c:112:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
CMakeFiles\lci.dir\build.make:109: recipe for target 'CMakeFiles/lci.dir/main.c.obj' failed
mingw32-make[2]: *** [CMakeFiles/lci.dir/main.c.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/lci.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/lci.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Hopefully the project isn't totally dead - would love to see it grow :)

**Comment by catb0t** [comment]
Just get readline -- looks like it wasn't added.

**Comment by catb0t** [comment]
Looks like you need `libreadline`. The project builds perfectly for me. Get libreadline: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html#Availability

**Comment by justinmeza** [comment]
Hi, @catbusstop! What @catb0t says is correct: `lci` requires you to install the `libreadline` library in order for it to build.
