### ISSUE TITLE
Variable resets to 0 completely randomly

### ISSUE THREAD

**Issue by iiDatKat** [justinmeza/lci#35]
I'm not sure if you can replicate this but I was trying to create a 99 bottles of beer program and I declared a variable called `BEERZVAR` and set it to 99. When I print it in a loop, and if I `lci` the program, the first thing I see when I scroll up is 0.

As you can see, I handle it by just checking if it's 0 (at the start only) and setting it to 99 manually.

Code is here, cause it's pretty long:
https://codeshare.io/f9J1h

Did I do something wrong with `I HAS A BEERZVAR` and `BEERZVAR R 99`? I know I can shorten it to `I HAS A BEERZVAR ITZ 99` but it gives me the same error.

**Comment by sjoqvist** [comment]
@iiDatKat The relevant code you're referring to is this, I believe
```
I HAS A BEERZVAR
BEERZVAR R 99

IM IN YR LOOP NERFIN YR BEERZVAR TIL BOTH SAEM BEERZVAR AN 1
    VISIBLE BEERZVA

    BTW removed from code snippet

IM OUTTA YR LOOP
```
Firstly, `BEERZVA` should probably be `BEERZVAR`, correct?

Secondly, I think that, in LOLCODE, this loop is _supposed_ to override `BEERZVAR` with a temporary variable initialized to 0. The official documentation says "That operation/function is applied to the [_sic_], which is temporary, and local to the loop." Is this different from your interpretation, or am I misunderstanding what you're talking about?

**Comment by iiDatKat** [comment]
@sjoqvist Yes, I meant `BEERZVAR`.
Yep, that makes total sense now. Thanks!
