### ISSUE TITLE
Error installing: There was a CMake error

### ISSUE THREAD

**Issue by ChristianLW** [justinmeza/lci#36]
Many people do the things, listed, in order to install.
They run `install.py` with their arguments.
They get the error `Error installing: There was a CMake error`.
Including me.
Please help.
I'm running Win 8.1 Pro 64-bit btw.

**Comment by Qiangong2** [comment]
Same with me. On win 8.1 and win 10

**Comment by dmuhs** [comment]
I managed to fix the errors by installing valgrind and doxygen. On Windows make sure that all dependencies are on your PATH variable.

**Comment by mackncheesiest** [comment]
On Windows 10, it works for me on Cygwin with CMake, Valgrind, Doxygen, and Git already installed as Cygwin packages.

**Comment by Sqeaky** [comment]
What generator is being used with CMake? I am unfamiliar with install.py but I wrote the CMakeLists.txt for Robot.

**Comment by emosGambler** [comment]
same here on windows 10...

**Comment by Citarosoftwarerepairs** [comment]
I run Linux (ubuntu) and I have similar problem

after i run make install, this comes out:

 [100%] Built target lci
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/lci
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot copy file "/home/citaro/lci/lci" to
  "/usr/local/bin/lci".


Makefile:128: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by ChristianLW** [comment]
This is such a stale, ancient issue that has very little info on it, so I'm going to close it.
