### ISSUE TITLE
'future' branch interpreter array errors

### ISSUE THREAD

**Issue by bfahrenfort** [justinmeza/lci#68]
I've compiled the future branch (which I cloned with `git clone --single-branch --branch future https://github.com/justinmeza/lci.git`) in Ubuntu 16 through the WSL, and when I try to use arrays in accordance with the Advanced Quick Reference, it causes an error.
CMake version: 3.16.3
Make version: GNU 4.2.1 x86_64-pc-linux-gnu
`lci --version`: v0.11.2

Code (filename is arrayz.lol):
`HAI 1.4`

`I HAS A array ITZ A BUKKIT`

`array'Z SRS 1 R 5`

`VISIBLE array'Z 1`

`KTHXBYE`

Run with: 
`lci arrayz.lol`

Error:
`arrayz.lol:7: expected identifier at: 1`

`arrayz.lol:7: unable to delete unknown identifier type`

`arrayz.lol:7: expected identifier at: 1`

`arrayz.lol:5 unable to store variable: array`

`arrayz.lol:7: unable to delete unknown identifier type`

Thanks!

**Comment by lipemesquita** [comment]
I believe there's something missing on the docs.

Take a look at this test:

HAI 1.3
	I HAS A foo ITZ A BUKKIT
	foo HAS A bar
	VISIBLE SUM OF 0 AN NOT foo'Z bar
KTHXBYE

(test/1.3-Tests/12-Arrays/2-SlotCreation/test.lol)

First you have to define that foo has a bar and then you can use it.
