### ISSUE TITLE
How can I build the project from the future branch?

### ISSUE THREAD

**Issue by DarkblooM-SR** [justinmeza/lci#81]
I was trying to test [httpd.lol](https://github.com/justinmeza/httpd.lol/) but ran into an [issue](https://github.com/justinmeza/httpd.lol/issues/1) and the apparent way to resolve it is to use the [future branch](https://github.com/justinmeza/lci/tree/future), except I get this error when running `make`:
```
[ 10%] Building C object CMakeFiles/lci.dir/main.c.o
/home/darkbloom/Downloads/lci/main.c:112:10: fatal error: readline/readline.h: No such file or directory
  112 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lci.dir/build.make:104: CMakeFiles/lci.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6923: CMakeFiles/lci.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
Enlightenment would be appreciated.

**Comment by justinmeza** [comment]
This likely means that the headers for the readline library are not installed.  If you are on Linux, it should be something like this:
```
sudo apt-get install libreadline-dev
```

**Comment by DarkblooM-SR** [comment]
That was it, thank you!

**Comment by justinmeza** [comment]
I am not aware of any implementations, but the LOLCODE 1.3 spec added support for [associative arrays and inheritance](https://github.com/justinmeza/lolcode-spec/blob/master/v1.3/lolcode-spec-v1.3.md#inheritance--prototyping), which can be used to do some object-oriented programming.

**Comment by justinmeza** [comment]
You can see what is implemented in `lci` by taking a look at some of the unit tests here: test/1.3-Tests/12-Arrays/13-Inheritance/2-Assignment.

**Comment by DarkblooM-SR** [comment]
Gotcha, thanks
